ManageActivities/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),

]

cadastros/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('cadastrar/disciplina', DisciplinaCreate.as_view(),
         name="cadastrar-disciplina"),
    path('cadastrar/bloco', BlocoCreate.as_view(), name="cadastrar-bloco"),
    path('cadastrar/atividade', AtividadeCreate.as_view(),
         name="cadastrar-atividade"),

    path('editar/disciplina/<int:pk>/', DisciplinaUpdate.as_view(),
         name="editar-disciplina"),
    path('editar/bloco/<int:pk>/', BlocoUpdate.as_view(),
         name="editar-bloco"),
    path('editar/atividade/<int:pk>/', AtividadeUpdate.as_view(),
         name="editar-atividade"),

    path('excluir/disciplina/<int:pk>/', DisciplinaDelete.as_view(),
         name="excluir-disciplina"),
    path('excluir/bloco/<int:pk>/', BlocoDelete.as_view(),
         name="excluir-bloco"),
    path('excluir/atividade/<int:pk>/', AtividadeDelete.as_view(),
         name="excluir-atividade"),

    path('listar/disciplinas/', DisciplinaList.as_view(),
         name="listar-disciplinas"),
    path('listar/blocos/', BlocoList.as_view(),
         name="listar-blocos"),
    path('listar/atividades/', AtividadeList.as_view(),
         name="listar-atividades"),
]

paginas/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', IndexView.as_view(), name="inicio"),
    path('home/', HomeView.as_view(), name="home"),

    # path('register/', RegisterView.as_view(), name="register")
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import User

class Disciplina(models.Model):
    nome = models.CharField(max_length=150)
    nomeProfessor = models.CharField(
        max_length=150, verbose_name="Nome do Professor(a)")
    emailProfessor = models.CharField(
        max_length=150, verbose_name="E-mail do Professor(a)")
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return "{}\n{} ({})".format(self.nome, self.nomeProfessor, self.emailProfessor)


class Bloco(models.Model):
    titulo = models.CharField(max_length=150, verbose_name="Título")
    dataInicio = models.DateField(verbose_name="Data de ínicio")
    dataFinal = models.DateField(verbose_name="Data final")
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return "{} (Data de ínicio {}- Data Final {})".format(self.titulo, self.dataInicio, self.dataFinal)


class Atividade(models.Model):
    titulo = models.CharField(max_length=150, verbose_name="Título")
    dataEntrega = models.DateField(verbose_name="Data de entrega")
    STATUS_ATIVIDADE = [
        ('PENDENTE', 'Pendente'),
        ('INICIADO', 'Iniciado'),
        ('FINALIZADO', 'Finalizado')
    ]
    status = models.CharField(
        max_length=10, choices=STATUS_ATIVIDADE, default='PENDENTE')
    isAvaliativo = models.BooleanField(verbose_name="É avaliativo?")
    descricao = models.CharField(max_length=180, verbose_name="Descrição")
    disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE,
                                   verbose_name="Disciplina")
    bloco_id = models.ForeignKey(Bloco, on_delete=models.CASCADE,
                                 verbose_name="Bloco")
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return "{} - {}\n{}\n{}\n{}\n{} ".format(self.titulo, self.disciplina, self.descricao, self.dataEntrega, self.isAvaliativo, self.status)

cadastros/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404

# Create your views here.
from .models import *
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin


class DisciplinaCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Disciplina
    fields = ['nome', 'nomeProfessor', 'emailProfessor']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-disciplinas')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        url = super().form_valid(form)
        return url

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = 'Cadastro da Disciplina'
        context['botao'] = 'Cadastrar'

        return context


class BlocoCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Bloco
    fields = ['titulo', 'dataInicio', 'dataFinal']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-blocos')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        url = super().form_valid(form)
        return url

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = 'Cadastro do Bloco'
        context['botao'] = 'Cadastrar'
        return context


class AtividadeCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Atividade
    fields = ['titulo', 'dataEntrega', 'status',
              'isAvaliativo', 'descricao', 'disciplina', 'bloco_id']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-atividades')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        url = super().form_valid(form)
        return url

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = 'Cadastro da Atividade'
        context['botao'] = 'Cadastrar'
        return context


class DisciplinaUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Disciplina
    fields = ['nome', 'nomeProfessor', 'emailProfessor']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-disciplinas')
    
    def get_object(self, queryset=None):
        self.object = get_object_or_404(Disciplina, pk=self.kwargs['pk'], usuario=self.request.user)
        return self.object

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = 'Alteração de Disciplina'
        context['botao'] = 'Alterar'
        return context


class BlocoUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Bloco
    fields = ['titulo', 'dataInicio', 'dataFinal']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-blocos')

    def get_object(self, queryset=None):
        self.object = get_object_or_404(Bloco, pk=self.kwargs['pk'], usuario=self.request.user)
        return self.object

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = 'Alteração de Bloco'
        context['botao'] = 'Alterar'
        return context


class AtividadeUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Atividade
    fields = ['titulo', 'dataEntrega', 'status',
              'isAvaliativo', 'descricao', 'disciplina', 'bloco_id']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-atividades')
    
    def get_object(self, queryset=None):
        self.object = get_object_or_404(Bloco, pk=self.kwargs['pk'], usuario=self.request.user)
        return self.object

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = 'Alteração da Atividade'
        context['botao'] = 'Alterar'
        return context


class DisciplinaDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    model = Disciplina
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-disciplinas')

    def get_object(self, queryset=None):
        self.object = get_object_or_404(Disciplina, pk=self.kwargs['pk'], usuario=self.request.user)
        return self.object

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = 'Disciplina'
        return context


class BlocoDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    model = Bloco
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-blocos')

    def get_object(self, queryset=None):
        self.object = get_object_or_404(Bloco, pk=self.kwargs['pk'], usuario=self.request.user)
        return self.object

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = 'Bloco'
        return context


class AtividadeDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    model = Atividade
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-atividades')

    def get_object(self, queryset=None):
        self.object = get_object_or_404(Atividade, pk=self.kwargs['pk'], usuario=self.request.user)
        return self.object
        
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = 'Atividade'
        return context


class DisciplinaList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Disciplina
    template_name = 'cadastros/listas/disciplinas.html'
    def get_queryset(self):
        self.object_list = Disciplina.objects.filter(usuario=self.request.user)
        return self.object_list


class BlocoList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Bloco
    template_name = 'cadastros/listas/blocos.html'
    def get_queryset(self):
        self.object_list = Bloco.objects.filter(usuario=self.request.user)
        return self.object_list

class AtividadeList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Atividade
    template_name = 'cadastros/listas/atividades.html'
    def get_queryset(self):
        self.object_list = Atividade.objects.filter(usuario=self.request.user)
        return self.object_list

cadastros/templates/cadastros/form-excluir.html
{% extends 'modelo.html' %} {% load static %}

{% block breadcrumb %}
    <div class="col-12 mt-4">
      <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href={% url 'inicio' %}>Home</a></li>
          <li class="breadcrumb-item"><a href="#">Exclusão</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{titulo}} {{object.id}}</li>
        </ol>
      </nav>
    </div>
{% endblock %}
{% block conteudo %}

<div class="container-fluid">
  <div class="text-center ">
    <p class="text-center m-4">Tem certeza que deseja excluir o registro " {{ object }}" ?</p>

  
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target=".bd-example-modal-sm">Deletar</button>
  </div>

  <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <form method="post">
          {% csrf_token %}
          <div class="row">
            <p class="text-center m-4">Tem certeza que deseja excluir esse registro?</p>
            
            <div class="col-12 justify-items-center m-2">
              <div class="text-center">
                <a href={% url 'inicio' %} class="btn btn-primary text-center">Voltar</a>
                <input type="submit" class="btn btn-danger text-center" value="Excluir">
              </div>
             
            </div>
          </div>
      </form>
      
      
      </div>
    </div>
  </div>
  </div>
</div>

{% endblock %}

cadastros/templates/cadastros/form.html
{% extends 'modelo.html' %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block breadcrumb %}
    <div class="col-12 mt-4">
      <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href={% url 'inicio' %}>Home</a></li>
          <li class="breadcrumb-item"><a href="#">Cadastrar</a></li>
          <!-- <li class="breadcrumb-item active" aria-current="page"> </li> -->
        </ol>
      </nav>
    </div>
{% endblock %}

{% block conteudo %}

<div class="container-fluid">
    <div class="card col-12 text-center">
      <div class="card-body">
          <h3>{{titulo}}</h3>
        <p class="card-text text-muted">
          Cadastre aqui as disciplinas, blocos ou atividades. Não esqueça de
          preeencher tudo ;)
        </p>
        <form action="" method="POST" class=" m-4 col-6 center">
          {% csrf_token %}  {{ form|crispy }}

          <button type="submit" class="btn btn-success m-2">{{botao}}</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block scripts %}
<script src="{% static 'js/plugins/jquery.mask.min.js' %}"></script>
<script>
  $(document).ready(function(){
  $('#id_dataEntrega').mask('00/00/0000');
  $('#id_dataInicio').mask('00/00/0000');
  $('#id_dataFinal').mask('00/00/0000');
});
</script> 
{% endblock %}